ndarry的索引(index),切割(slice)

In [7]:
import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

In [8]:
import random
random.randint(50,100)

78

In [9]:
np.random.randint(50, 101, size=5)
scores = np.random.randint(50,101, size=(50, 5))
scores.size
scores.shape

(50, 5)

In [21]:
scores[:, 0]
scores[:,0:1]

array([[ 96],
       [ 89],
       [ 54],
       [ 55],
       [ 99],
       [ 67],
       [ 66],
       [ 94],
       [ 86],
       [ 67],
       [ 98],
       [ 98],
       [ 99],
       [ 57],
       [ 59],
       [ 53],
       [ 56],
       [ 54],
       [ 72],
       [ 55],
       [ 50],
       [ 79],
       [ 61],
       [ 76],
       [ 58],
       [ 96],
       [ 93],
       [ 59],
       [ 72],
       [ 88],
       [ 82],
       [ 65],
       [ 98],
       [ 88],
       [ 71],
       [ 92],
       [ 83],
       [ 94],
       [ 55],
       [ 69],
       [ 79],
       [ 79],
       [ 78],
       [ 73],
       [ 79],
       [100],
       [ 70],
       [ 86],
       [ 87],
       [ 61]], dtype=int32)

In [18]:
scores[0,:]
scores[0:1,:]

array([[96, 72, 77, 85, 67]], dtype=int32)

In [20]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([79.4, 64. , 73.8, 63.6, 81.2, 64.2, 70.4, 80.4, 70.6, 68.6, 76.6,
       80.4, 84.4, 73.6, 74. , 69.6, 71.8, 72.8, 74.2, 65. , 72.6, 77. ,
       71.6, 67.4, 72.6, 78.4, 81.2, 78.2, 70. , 83.8, 76. , 70.4, 68.8,
       76.8, 62.4, 80.6, 71. , 68.6, 63. , 74. , 71.4, 68.4, 67.6, 63. ,
       79.8, 86.2, 81. , 80. , 77.6, 73.8])

In [23]:
#使用比較運算子
arr = np.random.randn(5)
arr > 0

array([ True,  True, False, False, False])

In [24]:
np.where(arr > 0, 1, 0)

array([1, 1, 0, 0, 0])

In [25]:
np.where(arr>0, 1, arr)

array([ 1.        ,  1.        , -0.01264332, -0.67683734, -0.52480534])