In [1]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 68,  52,  83,  97,  66],
       [ 84,  93,  81,  55,  73],
       [ 79,  88,  78,  58,  67],
       [ 79,  56,  65, 100,  83],
       [ 65,  75,  76,  93,  81]], dtype=int32)

In [18]:
scores [:, 0] + scores [:, 1] + scores [:, 2] + scores [:, 3] + scores [:, 4]

array([366, 386, 370, 383, 390], dtype=int32)

In [3]:
scores[:3, 2:]

array([[83, 97, 66],
       [81, 55, 73],
       [78, 58, 67]], dtype=int32)

In [9]:
scores [4]
scores [4, :]
scores [4:, :]

array([[65, 75, 76, 93, 81]], dtype=int32)

In [10]:
scores [:, :2]

array([[68, 52],
       [84, 93],
       [79, 88],
       [79, 56],
       [65, 75]], dtype=int32)

In [ ]:
### numpy 的統計工具

In [11]:
scores [:, 0] + scores [:, 1] + scores [:, 2] + scores [:, 3] + scores [:, 4]

array([366, 386, 370, 383, 390], dtype=int32)

In [12]:
#加總
np.sum(scores,axis=1)

array([366, 386, 370, 383, 390])

In [13]:
#平均
np.mean(scores, axis=1)

array([73.2, 77.2, 74. , 76.6, 78. ])

In [14]:
#最大
np.max(scores,axis=1)

array([ 97,  93,  88, 100,  93], dtype=int32)

In [15]:
#最小
np.min(scores,axis=1)

array([52, 55, 58, 56, 65], dtype=int32)

In [16]:
#中間數
np.median(scores,axis=1)

array([68., 81., 78., 79., 76.])

In [17]:
#標準差
np.std(scores,axis=1)

array([15.43243338, 12.8124939 , 10.41153207, 15.18683641,  9.1214034 ])