https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [2]:
import numpy as np

In [8]:
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [9]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.random.rand(3, 4)

array([[0.52113243, 0.88537295, 0.00404961, 0.28068613],
       [0.64008185, 0.25905218, 0.9208444 , 0.36897795],
       [0.4576336 , 0.28958348, 0.74129156, 0.90813285]])

In [15]:
scores = np.random.randint(50, 101, size=(50, 5))
scores

array([[ 88,  51,  89,  54,  73],
       [ 51,  82,  50,  86,  86],
       [ 51,  69,  92,  88,  77],
       [ 59,  89,  93,  83,  86],
       [ 86,  81,  61,  83,  99],
       [ 57,  79,  81,  97,  51],
       [ 68,  56,  73,  80,  70],
       [ 56,  78,  85,  52,  64],
       [ 58,  59,  73,  78,  93],
       [ 58,  58,  58,  63,  56],
       [ 84,  59,  83,  91,  79],
       [ 85,  84,  91,  86,  97],
       [ 56,  85,  91,  61,  78],
       [ 81,  70,  94,  71,  84],
       [ 91,  87,  83,  97,  98],
       [ 60,  98,  68,  64,  78],
       [ 64,  68,  55,  84,  55],
       [ 62,  81,  51,  72,  88],
       [ 63,  96,  91,  62,  72],
       [ 69,  99,  75,  88,  72],
       [ 92,  65,  51,  88,  94],
       [ 59,  82,  68,  63,  72],
       [ 50,  62,  58,  55,  83],
       [ 59,  73,  52,  54,  93],
       [ 55,  58,  86,  85,  79],
       [ 65,  91,  92,  97,  88],
       [ 60,  63,  90,  71,  84],
       [ 96,  93,  54, 100,  96],
       [ 50, 100,  53,  50,  51],
       [ 83,  